# Classification: SI > median
model: LogisticRegression
target: SI_above_median
features: null
cv_folds: 5
random_state: 42
hyperparameters:
  C: 1.0
  penalty: l2
output: artifacts/cls_si_med_model.joblib
reports:
  metrics: reports/cls_si_med_metrics.json
  figures_dir: reports/figures/cls_si_med
